targets:
  $default:
    builders:
      flutter_auto_export_first:
        enabled: true
      flutter_auto_export_second:
        enabled: true

builders:
  flutter_auto_export_first:
    import: "package:flutter_auto_export/files_exporter.dart"
    builder_factories: ["exporterGeneratorBuilder"]
    build_extensions: { ".dart": [".exports"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    runs_before: ["flutter_auto_export:flutter_auto_export_second"]
  flutter_auto_export_second:
    import: "package:flutter_auto_export/files_exporter.dart"
    builder_factories: ["exportsBuilder"]
    build_extensions: { "$lib$": [".exports.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
