name: flutter_auto_export
description: A new Flutter package that allows you to auto export types globally.
version: 1.1.0
homepage: https://github.com/AlbertoMonteiro/FlutterAutoExport

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  source_gen: ^1.4.0
  build: ^2.4.1
  build_resolvers: ^2.2.1
  meta: ^1.2.2
  glob: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.6